### PR TITLE
FIX Sanitise summary fields list before querying the DB

### LINKED ISSUE #44: Summary definition throws an error if value doesn't exist
It appears that an assumption is made that all values in `summary_fields` exist. I tried to build a registry and one of the values - an image source - did not exist. 
This caused a database exception, where the search query could not be run due to the non-existing field.

### PR DESCRIPTION
**Pull request by raissanorth**
Prior, an assumption was made within the RegistryPageController's queryList function that all values within the summaryFields list exists in the database. This caused a database exception when a query was run against non-existing summary fields such as method calls.

To resolve the issue, the commit adds some logic that removes any non database residing summary fields before trying to erroneously SELECT them.

Fixes #44

### CODE REVIEW

File: src/RegistryPageController.php [hunk 1]
```diff
@@ -312,13 +311,23 @@ protected function queryList(array $where, array $orderby, $start, $pageLength,
...
 
-        $resultColumns = $this->dataRecord->getDataSingleton()->summaryFields();
-        $resultColumns['ID'] = 'ID';
+        $summarisedModel = $this->dataRecord->getDataSingleton();
+        $resultColumns = $summarisedModel->summaryFields();
+
+        // Remove any non database residing summary fields before trying to erroneously SELECT them.
+        $resultDBOnlyColumns = [];
+        foreach ($resultColumns as $summaryFieldKey => $summaryFieldValue) {
+            if (!$summarisedModel->hasMethod("get{$summaryFieldKey}")) {
```
Comment (robbieaverill) [inline src/RegistryPageController.php]: `$summaryFieldKey` could legitimately be `getThumbnail`, so we'd need to check for `!...->hasMethod($summaryFieldKey) && !...->hasMethod("get{$summaryFieldKey}")` I think

Comment (dhensby) [reply src/RegistryPageController.php]: Hmm, a summary field should be a pointer to a field and not to a method. You want to follow the logic of core as closely as possible with this and I'm pretty sure they don't accept first class methods as values but the do accept pseudo properties (ie: properties populated by `get{name}`

Comment (NightJar) [reply src/RegistryPageController.php]: pseudo fields fall back to `__get`, which in turn relies on `hasField`:
https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/ORM/DataObject.php#L2479

It seems only templates check properties _and_ methods. So this is ready for merge.
